# Generated by Django 3.2.7 on 2021-09-14 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='icon',
        ),
    ]
